"""add group category

Revision ID: b34cc06907b3
Revises: 2d1ed02343d0
Create Date: 2026-08-12 20:30:17.674715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34cc06907b3'
down_revision: Union[str, Sequence[str], None] = '2d1ed02343d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('category', sa.Enum('PROJET', 'POLE', 'ANTENNE', name='category', native_enum=False, length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'category')
    # ### end Alembic commands ###
